#!/usr/bin/env python3
"""Vidlark blog generator. Python 3 standard library only, nothing to install.

Reads every post in content/blog/<slug>.md (front matter plus Markdown) and writes:
  website/blog/<slug>.html   one page per post
  website/blog/index.html    every post, newest first, filterable by category
  website/blog/feed.xml      the RSS feed
  website/sitemap.xml        every page and post, with lastmod
  website/index.html         the "From the blog" strip, between its two marker comments

Then it checks the whole site: JSON-LD parses, internal links and #anchors resolve, one h1 per
page, every image has alt text, titles and descriptions are the right length, no em dashes.

  python3 Tools/blog.py            build, then check
  python3 Tools/blog.py --check    check only, write nothing
  python3 Tools/blog.py --covers   first render a cover for any post whose cover file is missing
  python3 Tools/blog.py --strict   treat warnings as errors (exit code 1)

content/blog/README.md explains the front matter and the image rules.
"""
from __future__ import annotations

import argparse
import datetime as dt
import html
import json
import re
import struct
import subprocess
import sys
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content" / "blog"
SITE = ROOT / "website"
BLOG_OUT = SITE / "blog"
HOME = SITE / "index.html"

BASE = "https://vidlark.vercel.app"
GITHUB = "https://github.com/neel542/vidlark"
AUTHOR = "Neel Madhav"
AUTHOR_URL = "https://github.com/neel542"
LOGO = BASE + "/assets/icon-512.png"
WPM = 220  # reading speed for "N min read"

# Category: (url slug, the site's field colour). The colour is the post's head band and cover.
CATEGORIES = {
    "Guides": ("guides", "green"),
    "Comparisons": ("comparisons", "sky"),
    "Tutorials": ("tutorials", "pink"),
    "Use cases": ("use-cases", "sun"),
    "Behind the build": ("behind-the-build", "lime"),
}
FIELD_HEX = {"green": "#1fd17c", "sky": "#5d9cff", "pink": "#ff74b0", "sun": "#ffd43d", "lime": "#d6f64e"}

BLOG_TITLE = "Vidlark blog: guides to recording YouTube videos"
BLOG_DESCRIPTION = ("Guides, tutorials and comparisons for recording YouTube videos with your camera, "
                    "mic and screen on a Mac or Windows PC, with Vidlark, the free recorder.")
BLOG_LEAD = ("Guides, tutorials and comparisons for recording videos with your camera, mic and screen, "
             "on a Mac or a Windows PC.")

GENERATED = "<!-- Generated by Tools/blog.py from content/blog/{src}. Edit that file, then run python3 Tools/blog.py. -->"
STRIP_START = "<!-- blog:latest:start"
STRIP_END = "<!-- blog:latest:end -->"
EM_DASH = "\u2014"  # written as an escape so this file has none itself

RSS_SYMBOL = ('<symbol id="i-rss" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-width="1.75" '
              'stroke-linecap="round" stroke-linejoin="round"><path d="M4 11a9 9 0 0 1 9 9"/>'
              '<path d="M4 4a16 16 0 0 1 16 16"/><circle cx="5" cy="19" r="1"/></g></symbol>')


class Problems:
    def __init__(self):
        self.errors: list[str] = []
        self.warnings: list[str] = []

    def error(self, where, msg):
        self.errors.append(f"{where}: {msg}")

    def warn(self, where, msg):
        self.warnings.append(f"{where}: {msg}")


def esc(text) -> str:
    return html.escape(str(text), quote=True)


def write(path: Path, text: str) -> bool:
    """Write only when the content changed, so git diffs stay clean."""
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.write_text(text, encoding="utf-8")
    return True


def long_date(d: dt.date) -> str:
    return f"{d.day} {d.strftime('%B')} {d.year}"


def short_date(d: dt.date) -> str:
    return f"{d.day} {d.strftime('%b')} {d.year}"


def jsonld(data) -> str:
    text = json.dumps(data, ensure_ascii=False, indent=1).replace("</", "<\\/")
    return f'<script type="application/ld+json">\n{text}\n</script>'


# ---------------------------------------------------------------------------------------------
# Image sizes (PNG, JPEG, WebP, GIF), so every <img> gets width and height.

def image_size(path: Path):
    try:
        data = path.read_bytes()
    except OSError:
        return None
    if data[:8] == b"\x89PNG\r\n\x1a\n":
        return struct.unpack(">II", data[16:24])
    if data[:6] in (b"GIF87a", b"GIF89a"):
        return struct.unpack("<HH", data[6:10])
    if data[:4] == b"RIFF" and data[8:12] == b"WEBP":
        chunk = data[12:16]
        if chunk == b"VP8X":
            return int.from_bytes(data[24:27], "little") + 1, int.from_bytes(data[27:30], "little") + 1
        if chunk == b"VP8 ":
            w, h = struct.unpack("<HH", data[26:30])
            return w & 0x3FFF, h & 0x3FFF
        if chunk == b"VP8L":
            v = int.from_bytes(data[21:25], "little")
            return (v & 0x3FFF) + 1, ((v >> 14) & 0x3FFF) + 1
        return None
    if data[:2] == b"\xff\xd8":
        i = 2
        while i + 9 < len(data):
            if data[i] != 0xFF:
                i += 1
                continue
            marker = data[i + 1]
            if marker in (0xD8, 0x01, 0xFF) or 0xD0 <= marker <= 0xD7:
                i += 2 if marker != 0xFF else 1
                continue
            length = struct.unpack(">H", data[i + 2:i + 4])[0]
            if 0xC0 <= marker <= 0xCF and marker not in (0xC4, 0xC8, 0xCC):
                h, w = struct.unpack(">HH", data[i + 5:i + 9])
                return w, h
            i += 2 + length
    return None


def local_file(url: str):
    """The file in website/ that a site URL points to, or None. Handles cleanUrls (/how-to)."""
    if url.startswith(BASE):
        url = url[len(BASE):] or "/"
    if not url.startswith("/") or url.startswith("//"):
        return None
    path = url.split("#")[0].split("?")[0]
    if path in ("", "/"):
        return SITE / "index.html"
    rel = path.lstrip("/")
    candidates = [SITE / rel, SITE / (rel + ".html"), SITE / rel / "index.html"]
    for c in candidates:
        if c.is_file():
            return c
    return None


# ---------------------------------------------------------------------------------------------
# Front matter: the small YAML subset the README describes.

KEY_RE = re.compile(r"^([A-Za-z_][\w-]*):(?:[ \t]+(.*)|[ \t]*)$")


def indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def parse_scalar(raw: str):
    raw = raw.strip()
    if raw in (">", "|", ">-", "|-"):
        return ""
    if raw.startswith(('>', '|')) and raw[:2] in ("> ", "| "):
        raw = raw[2:].strip()
    if not raw:
        return ""
    if raw[0] == '"':
        if not raw.endswith('"') or len(raw) < 2:
            raise ValueError(f"a quoted value is not closed: {raw[:40]}")
        try:
            return json.loads(raw)
        except json.JSONDecodeError:
            return raw[1:-1]
    if raw[0] == "'":
        if not raw.endswith("'") or len(raw) < 2:
            raise ValueError(f"a quoted value is not closed: {raw[:40]}")
        return raw[1:-1].replace("''", "'")
    if raw.startswith("[") and raw.endswith("]"):
        inner = raw[1:-1].strip()
        if not inner:
            return []
        parts, cur, quote = [], "", None
        for ch in inner:
            if quote:
                cur += ch
                if ch == quote:
                    quote = None
            elif ch in "\"'":
                quote = ch
                cur += ch
            elif ch == ",":
                parts.append(cur)
                cur = ""
            else:
                cur += ch
        parts.append(cur)
        return [parse_scalar(p) for p in parts if p.strip()]
    raw = re.split(r"\s+#", raw, maxsplit=1)[0].strip()  # a comment after a plain value
    if raw in ("true", "false"):
        return raw == "true"
    return raw


def parse_front_matter(src: str):
    lines = src.split("\n")
    data = {}
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip() or line.lstrip().startswith("#"):
            i += 1
            continue
        if indent_of(line) != 0:
            raise ValueError(f"front matter line {i + 2} is indented but belongs to nothing: {line.strip()[:50]}")
        m = KEY_RE.match(line)
        if not m:
            raise ValueError(f"front matter line {i + 2} is not 'key: value': {line.strip()[:50]}")
        key, rest = m.group(1), (m.group(2) or "").strip()
        i += 1
        block = []
        while i < len(lines) and (not lines[i].strip() or indent_of(lines[i]) > 0):
            block.append(lines[i])
            i += 1
        while block and not block[-1].strip():
            block.pop()
        if rest and rest not in (">", "|", ">-", "|-"):
            data[key] = parse_scalar(" ".join([rest] + [b.strip() for b in block if b.strip()]))
        elif block and block[0].strip().startswith("-"):
            data[key] = parse_list(block)
        else:
            data[key] = " ".join(b.strip() for b in block if b.strip())
    return data


def parse_list(block: list[str]):
    items = []
    cur = None  # ["scalar", [parts]] or ["map", {key: [parts]}, last_key, item_indent]
    for line in block:
        if not line.strip():
            continue
        s = line.strip()
        ind = indent_of(line)
        if s == "-" or s.startswith("- "):
            content = s[1:].strip()
            m = KEY_RE.match(content)
            if m and not content.startswith(("'", '"')):
                cur = ["map", {m.group(1): [m.group(2) or ""]}, m.group(1), ind]
            else:
                cur = ["scalar", [content]]
            items.append(cur)
            continue
        if cur is None:
            raise ValueError(f"a list item must start with '- ': {s[:50]}")
        if cur[0] == "map":
            m = KEY_RE.match(s)
            if m and ind <= cur[3] + 2:
                cur[1][m.group(1)] = [m.group(2) or ""]
                cur[2] = m.group(1)
                continue
            cur[1][cur[2]].append(s)
        else:
            cur[1].append(s)
    out = []
    for item in items:
        if item[0] == "map":
            out.append({k: parse_scalar(" ".join(p for p in v if p.strip() not in (">", "|", ">-", "|-")))
                        for k, v in item[1].items()})
        else:
            out.append(parse_scalar(" ".join(item[1])))
    return out


# ---------------------------------------------------------------------------------------------
# Markdown: a small, careful converter for the subset posts use. Every piece of text is
# HTML-escaped; raw HTML in a post is shown as text, never passed through.

LIST_RE = re.compile(r"^( {0,12})([-*+]|\d{1,9}[.)])( +|$)(.*)$")
FENCE_RE = re.compile(r"^( {0,3})(`{3,}|~{3,})[ \t]*([\w+#.-]*)[ \t]*$")
HEADING_RE = re.compile(r"^ {0,3}(#{1,6})[ \t]+(.*?)[ \t]*#*[ \t]*$")
HR_RE = re.compile(r"^ {0,3}((\*[ \t]*){3,}|(-[ \t]*){3,}|(_[ \t]*){3,})$")
IMAGE_LINE_RE = re.compile(r'^!\[([^\]]*)\]\(\s*<?([^)\s>]+)>?(?:\s+"([^"]*)")?\s*\)$')
SAFE_SCHEMES = ("http://", "https://", "mailto:")


def slugify(text: str) -> str:
    text = re.sub(r"<[^>]+>", "", text)
    text = html.unescape(text).lower()
    text = re.sub(r"[^\w\s-]", "", text)
    text = re.sub(r"[\s_]+", "-", text).strip("-")
    return re.sub(r"-{2,}", "-", text) or "section"


def strip_md(text: str) -> str:
    """Markdown inline syntax to plain text (for JSON-LD and the table of contents)."""
    text = re.sub(r"!\[([^\]]*)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"<(https?://[^>]+)>", r"\1", text)
    text = re.sub(r"(\*\*|__|~~)(.+?)\1", r"\2", text)
    text = re.sub(r"(?<!\w)[*_](\S.*?\S|\S)[*_](?!\w)", r"\1", text)
    text = re.sub(r"`+([^`]+)`+", r"\1", text)
    text = re.sub(r"\\([\\`*_{}\[\]()#+\-.!|<>~])", r"\1", text)
    return text.strip()


def is_table_sep(line: str) -> bool:
    if "-" not in line or "|" not in line:
        return False
    cells = split_row(line)
    return bool(cells) and all(re.match(r"^:?-+:?$", c) for c in cells)


def split_row(line: str):
    s = line.strip()
    if s.startswith("|"):
        s = s[1:]
    if s.endswith("|") and not s.endswith("\\|"):
        s = s[:-1]
    return [c.strip().replace("\\|", "|") for c in re.split(r"(?<!\\)\|", s)]


class Markdown:
    def __init__(self, where: str, problems: Problems):
        self.where = where
        self.problems = problems
        self.headings: list[tuple[int, str, str]] = []  # (level, id, plain text)
        self.ids: set[str] = set()
        self.links: list[str] = []
        self.images: list[str] = []
        self._store: list[str] = []

    # ---- blocks

    def convert(self, text: str) -> str:
        lines = text.replace("\r\n", "\n").replace("\t", "    ").split("\n")
        return self.blocks(lines)

    def blocks(self, lines: list[str], tight: bool = False) -> str:
        out: list[str] = []
        para: list[str] = []
        n = len(lines)
        i = 0

        def flush():
            if para:
                text = self.inline(" ".join(p.strip() for p in para))
                out.append(text if tight else f"<p>{text}</p>")
                para.clear()

        while i < n:
            line = lines[i]
            s = line.strip()
            if not s:
                flush()
                i += 1
                continue

            m = FENCE_RE.match(line)
            if m:
                flush()
                fence, lang, ind = m.group(2), m.group(3), len(m.group(1))
                close = re.compile(r"^ {0,3}" + re.escape(fence[0]) + "{" + str(len(fence)) + r",}[ \t]*$")
                i += 1
                code = []
                while i < n and not close.match(lines[i]):
                    code.append(lines[i][ind:] if lines[i][:ind].strip() == "" else lines[i].lstrip())
                    i += 1
                if i >= n:
                    self.problems.warn(self.where, "a code block is not closed with ```")
                i += 1
                cls = f' class="language-{esc(lang.lower())}"' if lang else ""
                out.append(f'<pre class="code"><code{cls}>{esc(chr(10).join(code))}</code></pre>')
                continue

            m = HEADING_RE.match(line)
            if m:
                flush()
                level = len(m.group(1))
                if level == 1:
                    self.problems.warn(self.where, "'# ' in the body is shown as '## ': the title is the page's only h1")
                    level = 2
                level = min(level, 4)
                inner = self.inline(m.group(2))
                plain = strip_md(m.group(2))
                hid = slugify(plain)
                base, k = hid, 2
                while hid in self.ids:
                    hid = f"{base}-{k}"
                    k += 1
                self.ids.add(hid)
                self.headings.append((level, hid, plain))
                out.append(f'<h{level} id="{hid}">{inner}</h{level}>')
                i += 1
                continue

            if HR_RE.match(line):
                flush()
                out.append("<hr>")
                i += 1
                continue

            if s.startswith(">"):
                flush()
                quote = []
                while i < n and lines[i].strip().startswith(">"):
                    q = lines[i].strip()[1:]
                    quote.append(q[1:] if q.startswith(" ") else q)
                    i += 1
                out.append(f'<blockquote class="note">\n{self.blocks(quote)}\n</blockquote>')
                continue

            if "|" in s and i + 1 < n and is_table_sep(lines[i + 1]):
                flush()
                head = split_row(line)
                aligns = []
                for c in split_row(lines[i + 1]):
                    aligns.append("center" if c.startswith(":") and c.endswith(":") else
                                  "right" if c.endswith(":") else "left" if c.startswith(":") else "")
                i += 2
                rows = []
                while i < n and lines[i].strip() and "|" in lines[i]:
                    rows.append(split_row(lines[i]))
                    i += 1

                def cell(tag, text, col):
                    a = aligns[col] if col < len(aligns) else ""
                    style = f' style="text-align:{a}"' if a and a != "left" else ""
                    return f"<{tag}{style}>{self.inline(text)}</{tag}>"

                thead = "".join(cell("th", c, k) for k, c in enumerate(head))
                body = "\n".join("<tr>" + "".join(cell("td", r[k] if k < len(r) else "", k)
                                                  for k in range(len(head))) + "</tr>" for r in rows)
                out.append(f'<div class="table-wrap"><table class="table">\n<thead><tr>{thead}</tr></thead>\n'
                           f'<tbody>\n{body}\n</tbody>\n</table></div>')
                continue

            lm = LIST_RE.match(line)
            if lm and (lm.group(4).strip() or not para):
                flush()
                html_list, i = self.parse_list(lines, i)
                out.append(html_list)
                continue

            m = IMAGE_LINE_RE.match(s)
            if m and not para and (i + 1 >= n or not lines[i + 1].strip()):
                flush()
                out.append(self.figure(m.group(1), m.group(2), m.group(3)))
                i += 1
                continue

            para.append(line)
            i += 1
        flush()
        return "\n".join(out)

    def parse_list(self, lines: list[str], i: int):
        n = len(lines)
        first = LIST_RE.match(lines[i])
        base = len(first.group(1))
        ordered = first.group(2)[0].isdigit()
        start = int(first.group(2)[:-1]) if ordered else 1
        items: list[list[str]] = []
        loose = False

        def sibling(line):
            m = LIST_RE.match(line)
            return m and len(m.group(1)) == base and m.group(2)[0].isdigit() == ordered

        while i < n and sibling(lines[i]):
            m = LIST_RE.match(lines[i])
            content_indent = len(m.group(1)) + len(m.group(2)) + max(1, len(m.group(3)))
            item = [m.group(4)]
            i += 1
            while i < n:
                line = lines[i]
                if not line.strip():
                    j = i
                    while j < n and not lines[j].strip():
                        j += 1
                    if j < n and indent_of(lines[j]) >= content_indent:
                        item.extend([""] * (j - i))
                        i = j
                        continue
                    break
                ind = indent_of(line)
                m2 = LIST_RE.match(line)
                if m2 and ind <= base:
                    break
                if ind >= content_indent or (m2 and ind > base):
                    item.append(line[min(ind, content_indent):])
                    i += 1
                    continue
                s = line.strip()
                if s.startswith(("#", "```", "~~~", ">", "|")):
                    break
                item.append(s)  # a lazy continuation of the item's text
                i += 1
            if "" in item:
                loose = True
            items.append(item)
            j = i
            while j < n and not lines[j].strip():
                j += 1
            if j > i and j < n and sibling(lines[j]):
                loose = True
                i = j
            elif j > i:
                break
        tag = "ol" if ordered else "ul"
        attrs = f' start="{start}"' if ordered and start != 1 else ""
        body = "\n".join(f"<li>{self.blocks(item, tight=not loose)}</li>" for item in items)
        return f"<{tag}{attrs}>\n{body}\n</{tag}>", i

    def figure(self, alt: str, src: str, caption) -> str:
        img = self.img(alt, src, lazy=True)
        tall = ""
        f = local_file(src)
        size = image_size(f) if f else None
        if size and size[1] > size[0]:
            tall = " tall"
        cap = f"<figcaption>{self.inline(caption)}</figcaption>" if caption else ""
        return f'<figure class="post-fig"><div class="shot{tall}">{img}</div>{cap}</figure>'

    def img(self, alt: str, src: str, lazy=True) -> str:
        alt = strip_md(alt)
        if not alt.strip():
            self.problems.error(self.where, f"the image {src} has no alt text: write ![what it shows]({src})")
        url = self.safe_url(src)
        self.images.append(src)
        dims = ""
        f = local_file(src)
        if src.startswith("/"):
            if not f:
                self.problems.error(self.where, f"the image {src} is not in website/")
            else:
                size = image_size(f)
                if size:
                    dims = f' width="{size[0]}" height="{size[1]}"'
        loading = ' loading="lazy" decoding="async"' if lazy else ""
        return f'<img src="{esc(url)}" alt="{esc(alt)}"{dims}{loading}>'

    def safe_url(self, url: str) -> str:
        u = url.strip()
        low = u.lower()
        if ":" in low.split("/")[0] and not low.startswith(SAFE_SCHEMES):
            self.problems.error(self.where, f"the link {u} uses a scheme that is not allowed")
            return "#"
        return u

    # ---- inline

    def _keep(self, rendered: str) -> str:
        self._store.append(rendered)
        return f"\x00{len(self._store) - 1}\x00"

    def inline(self, text: str) -> str:
        text = re.sub(r"(`+)(.+?)\1", lambda m: self._keep(f"<code>{esc(m.group(2).strip())}</code>"), text)
        text = re.sub(r"\\([\\`*_{}\[\]()#+\-.!|<>~])", lambda m: self._keep(esc(m.group(1))), text)
        text = re.sub(r"<(https?://[^\s>]+)>",
                      lambda m: self._keep(self.link(m.group(1), esc(m.group(1)), None)), text)
        text = re.sub(r'!\[([^\]]*)\]\(\s*<?([^)\s>]+)>?(?:\s+"([^"]*)")?\s*\)',
                      lambda m: self._keep(self.img(m.group(1), m.group(2))), text)
        text = re.sub(r'\[([^\]]+)\]\(\s*<?([^)\s>]+)>?(?:\s+"([^"]*)")?\s*\)',
                      lambda m: self._keep(self.link(m.group(2), self.emphasis(esc(m.group(1))), m.group(3))), text)
        text = self.emphasis(esc(text))
        while "\x00" in text:
            text = re.sub(r"\x00(\d+)\x00", lambda m: self._store[int(m.group(1))], text)
        return text

    @staticmethod
    def emphasis(text: str) -> str:
        text = re.sub(r"\*\*(?=\S)(.+?)(?<=\S)\*\*", r"<strong>\1</strong>", text)
        text = re.sub(r"(?<!\w)__(?=\S)(.+?)(?<=\S)__(?!\w)", r"<strong>\1</strong>", text)
        text = re.sub(r"~~(?=\S)(.+?)(?<=\S)~~", r"<del>\1</del>", text)
        text = re.sub(r"(?<![\w*])\*(?=[^\s*])(.+?)(?<=[^\s*])\*(?![\w*])", r"<em>\1</em>", text)
        text = re.sub(r"(?<![\w_])_(?=[^\s_])(.+?)(?<=[^\s_])_(?![\w_])", r"<em>\1</em>", text)
        return text

    def link(self, url: str, label_html: str, title) -> str:
        url = self.safe_url(url)
        self.links.append(url)
        t = f' title="{esc(title)}"' if title else ""
        return f'<a href="{esc(url)}"{t}>{label_html}</a>'


# ---------------------------------------------------------------------------------------------
# Posts

REQUIRED = ["title", "description", "date", "keyword", "category", "cover", "cover_alt"]


class Post:
    def __init__(self, path: Path):
        self.path = path
        self.slug = path.stem
        self.src = path.name
        self.meta: dict = {}
        self.body = ""
        self.html = ""
        self.headings: list = []
        self.words = 0
        self.faq: list = []
        self.related: list[str] = []
        self.draft = False

    @property
    def url(self):
        return f"{BASE}/blog/{self.slug}"

    @property
    def path_url(self):
        return f"/blog/{self.slug}"

    @property
    def cat_slug(self):
        return CATEGORIES[self.meta["category"]][0]

    @property
    def colour(self):
        return CATEGORIES[self.meta["category"]][1]

    @property
    def social(self):
        """A 1200x630 JPG beside the cover, if Tools/blog_cover.js made one, for link previews."""
        p = local_file(self.social_path)
        return self.social_path if p else None

    @property
    def social_path(self):
        return f"/assets/img/blog/{self.slug}-social.jpg"

    def page_title(self):
        t = self.meta.get("seo_title") or self.meta["title"]
        if "vidlark" not in t.lower() and len(t) + len(" | Vidlark") <= 60:
            t += " | Vidlark"
        return t


def load_post(path: Path, problems: Problems):
    post = Post(path)
    where = f"content/blog/{path.name}"
    text = path.read_text(encoding="utf-8")
    if EM_DASH in text:
        line = text[:text.index(EM_DASH)].count("\n") + 1
        problems.error(where, f"line {line} has an em dash. Use a comma, a colon, a full stop or brackets")
    if not re.match(r"^[a-z0-9]+(-[a-z0-9]+)*$", post.slug):
        problems.error(where, "the file name is the URL: use lowercase letters, numbers and hyphens only")
    elif len(post.slug) > 70:
        problems.warn(where, "the file name (the URL) is long; keep it under 70 characters")
    m = re.match(r"^---[ \t]*\n(.*?)\n---[ \t]*(?:\n|$)", text.replace("\r\n", "\n"), re.S)
    if not m:
        problems.error(where, "the file must start with front matter between two '---' lines")
        return None
    try:
        meta = parse_front_matter(m.group(1))
    except ValueError as e:
        problems.error(where, str(e))
        return None
    post.meta = meta
    post.body = text.replace("\r\n", "\n")[m.end():]
    post.draft = meta.get("draft") is True

    for key in REQUIRED:
        if not isinstance(meta.get(key), str) or not meta.get(key, "").strip():
            problems.error(where, f"'{key}' is missing or empty")
    if any(not isinstance(meta.get(k), str) or not meta.get(k, "").strip() for k in REQUIRED):
        return None
    known = set(REQUIRED) | {"seo_title", "updated", "faq", "related", "draft"}
    for key in meta:
        if key not in known:
            problems.warn(where, f"'{key}' is not a front matter field the generator knows; it is ignored")

    title, desc = meta["title"].strip(), meta["description"].strip()
    if len(title) > 60:
        problems.warn(where, f"title is {len(title)} characters; keep it under 60")
    if meta.get("seo_title") and len(meta["seo_title"]) > 60:
        problems.warn(where, f"seo_title is {len(meta['seo_title'])} characters; keep it under 60")
    if not 140 <= len(desc) <= 160:
        problems.warn(where, f"description is {len(desc)} characters; aim for 140 to 160")

    for key in ("date", "updated"):
        if key in meta:
            try:
                meta[key] = dt.date.fromisoformat(str(meta[key]))
            except ValueError:
                problems.error(where, f"'{key}' must be a date like 2026-10-09")
                return None
    meta.setdefault("updated", meta["date"])
    if meta["updated"] < meta["date"]:
        problems.error(where, "'updated' is before 'date'")
    if meta["date"] > dt.date.today():
        problems.warn(where, f"date {meta['date']} is in the future; the post is still built")

    if meta["category"] not in CATEGORIES:
        problems.error(where, f"category must be one of: {', '.join(CATEGORIES)}")
        return None

    cover = meta["cover"]
    if not cover.startswith("/assets/img/blog/"):
        problems.error(where, "cover must be a path under /assets/img/blog/")
    elif not local_file(cover):
        problems.error(where, f"the cover {cover} is not in website/. Make one with: "
                              f"node Tools/blog_cover.js {post.slug} \"{title}\" \"{meta['category']}\"")
    else:
        size = image_size(local_file(cover))
        meta["cover_size"] = size
        if not size:
            problems.error(where, f"cannot read the size of {cover}; use WebP, JPG or PNG")
        elif size[0] < 1200 or abs(size[0] / size[1] - 16 / 9) > 0.02:
            problems.warn(where, f"the cover is {size[0]}x{size[1]}; it should be 1600x900 (16:9, at least 1200 wide)")
        kb = local_file(cover).stat().st_size // 1024
        if kb > 300:
            problems.warn(where, f"the cover is {kb} KB; keep it under 300 KB")

    faq = meta.get("faq", [])
    if faq:
        if not isinstance(faq, list) or not all(isinstance(x, dict) and str(x.get("q", "")).strip()
                                                and str(x.get("a", "")).strip() for x in faq):
            problems.error(where, "faq must be a list of items, each with q: and a:")
            faq = []
    post.faq = faq
    related = meta.get("related", [])
    if isinstance(related, str):
        related = [related]
    post.related = [str(r).strip() for r in related if str(r).strip()]

    md = Markdown(where, problems)
    post.html = md.convert(post.body)
    for x in faq:  # collect the answers' links, so they are checked too
        md.inline(str(x["q"]))
        md.inline(str(x["a"]))
    post.headings = md.headings
    post.links = md.links
    plain = re.sub(r"```.*?```", " ", post.body, flags=re.S)
    post.words = len(re.findall(r"[A-Za-z0-9][A-Za-z0-9'.,-]*", strip_md(plain)))
    if post.words < 300:
        problems.warn(where, f"the body is {post.words} words; most posts should be longer")

    kw = meta["keyword"].lower()
    if kw not in (title + " " + meta.get("seo_title", "")).lower():
        problems.warn(where, f"the keyword '{meta['keyword']}' is not in the title or seo_title")
    if kw not in desc.lower():
        problems.warn(where, f"the keyword '{meta['keyword']}' is not in the description")
    first = " ".join(strip_md(post.body).split()[:120]).lower()
    if kw not in first:
        problems.warn(where, f"the keyword '{meta['keyword']}' is not in the first 120 words")
    return post


def check_post_links(post: Post, slugs: set, problems: Problems):
    where = f"content/blog/{post.src}"
    for r in post.related:
        if r == post.slug:
            problems.error(where, "related lists the post itself")
        elif r not in slugs:
            problems.error(where, f"related post '{r}' does not exist (content/blog/{r}.md)")
    for url in post.links:
        if url.startswith("#"):
            if url[1:] not in {h[1] for h in post.headings} and url != "#questions":
                problems.error(where, f"the link {url} points to no heading in this post")
            continue
        if url.startswith("/blog/") and url.split("#")[0].split("/")[-1] in slugs:
            continue
        if url.startswith("/") and not local_file(url):
            problems.error(where, f"the link {url} goes to no page on the site")


def related_posts(post: Post, posts: list[Post]) -> list[Post]:
    by_slug = {p.slug: p for p in posts}
    chosen = [by_slug[s] for s in post.related if s in by_slug and s != post.slug]
    for p in posts:  # newest first already
        if len(chosen) >= 3:
            break
        if p is not post and p not in chosen and p.meta["category"] == post.meta["category"]:
            chosen.append(p)
    for p in posts:
        if len(chosen) >= 3:
            break
        if p is not post and p not in chosen:
            chosen.append(p)
    return chosen[:3]


# ---------------------------------------------------------------------------------------------
# Page pieces, taken from website/index.html so the header, footer, icons and stylesheet
# version always match the hand-written pages.

class Shell:
    def __init__(self, problems: Problems):
        home = HOME.read_text(encoding="utf-8")
        m = re.search(r'<header class="nav[^"]*">.*?</header>', home, re.S)
        f = re.search(r'<footer class="foot">.*?</footer>', home, re.S)
        v = re.search(r"/assets/site\.css\?v=(\w+)", home)
        j = re.search(r"/assets/site\.js\?v=(\w+)", home)
        if not (m and f and v and j):
            raise SystemExit("website/index.html: cannot find the header, footer or stylesheet link to copy")
        header = re.sub(r'^<header class="nav[^"]*">', '<header class="nav">', m.group(0))
        self.header = re.sub(r'\s+aria-current="[^"]*"', "", header)
        if 'href="/blog"' not in self.header:
            problems.error("website/index.html", "the navigation has no Blog link")
        self.footer = f.group(0)
        self.css = v.group(1)
        self.js = j.group(1)
        symbols = []
        for sid in ("i-check", "i-github", "i-arrow", "i-menu"):
            s = re.search(r'<symbol id="' + sid + r'".*?</symbol>', home, re.S)
            if s:
                symbols.append(s.group(0))
        symbols.append(RSS_SYMBOL)
        self.sprite = ('<svg width="0" height="0" style="position:absolute" aria-hidden="true">\n  <defs>\n'
                       '    <!-- Most icons are from Lucide (lucide.dev), ISC License: /assets/icons-license.txt -->\n    '
                       + "\n    ".join(symbols) + "\n  </defs>\n</svg>")

    def nav(self, current: str) -> str:
        return self.header.replace('<a href="/blog">', f'<a href="/blog" aria-current="{current}">', 1)

    def head(self, *, title, description, canonical, image, image_alt, image_size, theme, og_type="website",
             extra="", data=None) -> str:
        w, h = image_size or (1200, 630)
        parts = [
            '<!doctype html>', '<html lang="en">', '<head>', '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            f"<title>{esc(title)}</title>",
            f'<meta name="description" content="{esc(description)}">',
            f'<link rel="canonical" href="{esc(canonical)}">',
            '<meta name="robots" content="index, follow, max-image-preview:large">',
            f'<meta name="theme-color" content="{theme}">',
            '<meta property="og:site_name" content="Vidlark">',
            f'<meta property="og:type" content="{og_type}">',
            f'<meta property="og:title" content="{esc(title)}">',
            f'<meta property="og:description" content="{esc(description)}">',
            f'<meta property="og:url" content="{esc(canonical)}">',
            f'<meta property="og:image" content="{esc(BASE + image)}">',
            f'<meta property="og:image:width" content="{w}">',
            f'<meta property="og:image:height" content="{h}">',
            f'<meta property="og:image:alt" content="{esc(image_alt)}">',
        ]
        if extra:
            parts.append(extra)
        parts += [
            '<meta name="twitter:card" content="summary_large_image">',
            f'<meta name="twitter:title" content="{esc(title)}">',
            f'<meta name="twitter:description" content="{esc(description)}">',
            f'<meta name="twitter:image" content="{esc(BASE + image)}">',
            f'<meta name="twitter:image:alt" content="{esc(image_alt)}">',
            '<link rel="icon" href="/favicon.ico" sizes="32x32">',
            '<link rel="icon" href="/assets/mark.svg" type="image/svg+xml">',
            '<link rel="apple-touch-icon" href="/assets/apple-touch-icon.png">',
            '<link rel="manifest" href="/site.webmanifest">',
            '<link rel="alternate" type="application/rss+xml" title="Vidlark blog" href="/blog/feed.xml">',
            '<link rel="preconnect" href="https://fonts.googleapis.com">',
            '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
            '<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wdth,wght@12..96,75..100,400..800'
            '&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">',
            f'<link rel="stylesheet" href="/assets/site.css?v={self.css}">',
        ]
        if data:
            parts.append(jsonld(data))
        parts.append("</head>")
        return "\n".join(parts)

    def tail(self) -> str:
        return f"{self.footer}\n\n<script src=\"/assets/site.js?v={self.js}\" defer></script>\n</body>\n</html>\n"


def publisher():
    return {"@type": "Organization", "name": "Vidlark", "url": BASE + "/",
            "logo": {"@type": "ImageObject", "url": LOGO, "width": 512, "height": 512}}


def crumbs_html(items) -> str:
    lis = []
    for name, href in items:
        if href:
            lis.append(f'<li><a href="{esc(href)}">{esc(name)}</a></li>')
        else:
            lis.append(f'<li aria-current="page">{esc(name)}</li>')
    return f'<nav class="crumbs" aria-label="Breadcrumb"><ol>{"".join(lis)}</ol></nav>'


def crumbs_data(items):
    return {"@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": k + 1, "name": name, "item": BASE + url}
        for k, (name, url) in enumerate(items)]}


def card(post: Post, level: int = 3) -> str:
    size = post.meta.get("cover_size") or (1600, 900)
    d = post.meta["date"]
    mins = max(1, round(post.words / WPM))
    return (
        f'<article class="post-card" data-category="{post.cat_slug}" style="--c:var(--{post.colour})">'
        f'<img src="{esc(post.meta["cover"])}" alt="" width="{size[0]}" height="{size[1]}" loading="lazy" decoding="async">'
        f'<div class="post-card-body">'
        f'<p class="post-cat"><i aria-hidden="true"></i>{esc(post.meta["category"])}</p>'
        f'<h{level}><a href="{post.path_url}">{esc(post.meta["title"])}</a></h{level}>'
        f'<p class="post-card-desc">{esc(post.meta["description"])}</p>'
        f'<p class="post-card-meta"><time datetime="{d.isoformat()}">{short_date(d)}</time> · {mins} min read</p>'
        f"</div></article>"
    )


def cta_box() -> str:
    return (
        '<aside class="post-cta" aria-labelledby="get-vidlark">\n'
        '  <h2 id="get-vidlark">Get Vidlark free</h2>\n'
        '  <p>A free, open source recorder for Mac and Windows. One button records your camera, mic and screen, '
        'and makes the finished video. No account, no watermark, no time limit.</p>\n'
        '  <div class="actions">\n'
        f'    <a class="btn" href="{GITHUB}"><svg aria-hidden="true"><use href="#i-github"/></svg>Get it on GitHub</a>\n'
        '    <a class="btn ghost" href="/how-to">How to install it<svg aria-hidden="true"><use href="#i-arrow"/></svg></a>\n'
        '  </div>\n'
        '  <p class="post-cta-fine"><a href="/how-to#mac">On a Mac</a>: built free from its code, by Claude Code or by hand. '
        '<a href="/how-to#windows">On Windows 11</a>: a beta zip to download.</p>\n'
        "</aside>"
    )


def render_post(post: Post, posts: list[Post], shell: Shell) -> str:
    m = post.meta
    d, u = m["date"], m["updated"]
    mins = max(1, round(post.words / WPM))
    cover = m["cover"]
    size = m.get("cover_size") or (1600, 900)
    social = post.social
    og_image, og_size = (social, (1200, 630)) if social else (cover, size)
    h2s = [h for h in post.headings if h[0] == 2]
    show_toc = len(h2s) >= 3 and post.words >= 700

    data = {"@context": "https://schema.org", "@graph": [
        {"@type": "BlogPosting", "@id": post.url + "#post",
         "mainEntityOfPage": {"@type": "WebPage", "@id": post.url},
         "url": post.url, "headline": m["title"], "description": m["description"],
         "image": [BASE + cover] + ([BASE + social] if social else []),
         "datePublished": d.isoformat(), "dateModified": u.isoformat(),
         "author": {"@type": "Person", "name": AUTHOR, "url": AUTHOR_URL},
         "publisher": publisher(), "articleSection": m["category"], "keywords": m["keyword"],
         "wordCount": post.words, "inLanguage": "en",
         "isPartOf": {"@type": "Blog", "@id": BASE + "/blog#blog", "name": "Vidlark blog", "url": BASE + "/blog"}},
        crumbs_data([("Home", "/"), ("Blog", "/blog"), (m["title"], post.path_url)]),
    ]}
    if post.faq:
        data["@graph"].append({"@type": "FAQPage", "mainEntity": [
            {"@type": "Question", "name": strip_md(str(x["q"])),
             "acceptedAnswer": {"@type": "Answer", "text": strip_md(str(x["a"]))}} for x in post.faq]})

    extra = "\n".join([
        f'<meta name="author" content="{AUTHOR}">',
        f'<meta property="article:published_time" content="{d.isoformat()}">',
        f'<meta property="article:modified_time" content="{u.isoformat()}">',
        f'<meta property="article:section" content="{esc(m["category"])}">',
        f'<meta property="article:tag" content="{esc(m["keyword"])}">',
    ])
    head = shell.head(title=post.page_title(), description=m["description"], canonical=post.url,
                      image=og_image, image_alt=m["cover_alt"], image_size=og_size,
                      theme=FIELD_HEX[post.colour], og_type="article", extra=extra, data=data)

    updated = (f' · <span>Updated <time datetime="{u.isoformat()}">{long_date(u)}</time></span>'
               if u != d else "")
    toc = ""
    if show_toc:
        colours = ["green", "sky", "pink", "sun", "lime"]
        links = [f'<a href="#{hid}"><i style="background:var(--{colours[k % 5]})"></i>{esc(text)}</a>'
                 for k, (_, hid, text) in enumerate(h2s)]
        if post.faq:
            links.append(f'<a href="#questions"><i style="background:var(--{colours[len(h2s) % 5]})"></i>Questions</a>')
        toc = ('<nav class="toc" aria-label="On this page"><p class="toc-title">On this page</p>\n'
               + "\n".join(links) + "\n</nav>\n")
    faq = ""
    if post.faq:
        md = Markdown(f"content/blog/{post.src} faq", Problems())
        items = "\n".join(f'<div class="faq-item"><h3>{md.inline(str(x["q"]))}</h3><p>{md.inline(str(x["a"]))}</p></div>'
                          for x in post.faq)
        faq = f'<section class="faq" id="questions" aria-labelledby="questions-title">\n<h2 id="questions-title">Questions</h2>\n<div class="faq-list">\n{items}\n</div>\n</section>\n'
    related = related_posts(post, posts)
    related_html = ""
    if related:
        related_html = ('<section class="band mist related" aria-labelledby="keep-reading">\n  <div class="wrap">\n'
                        '    <div class="strip-head"><h2 id="keep-reading">Keep reading</h2>'
                        '<a class="btn ghost" href="/blog">All posts<svg aria-hidden="true"><use href="#i-arrow"/></svg></a></div>\n'
                        '    <div class="post-cards">\n' + "\n".join(card(p, 3) for p in related) + "\n    </div>\n  </div>\n</section>\n")

    return f"""{head}
<body>
{GENERATED.format(src=post.src)}
{shell.sprite}

<a class="skip" href="#main">Skip to the content</a>

{shell.nav("true")}

<main id="main">
<article class="post">
<header class="band post-head" style="--c:var(--{post.colour})">
  <div class="wrap">
    {crumbs_html([("Home", "/"), ("Blog", "/blog"), (m["title"], None)])}
    <p class="post-cat chip"><a href="/blog#{post.cat_slug}"><i aria-hidden="true"></i>{esc(m["category"])}</a></p>
    <h1>{esc(m["title"])}</h1>
    <p class="post-lead">{esc(m["description"])}</p>
    <p class="post-meta">By <a href="{AUTHOR_URL}" rel="author">{AUTHOR}</a> · <time datetime="{d.isoformat()}">{long_date(d)}</time>{updated} · {mins} min read</p>
  </div>
</header>

<div class="post-body">
  <div class="wrap post-layout{' has-toc' if show_toc else ''}">
    <aside class="post-side">
{toc}      <p class="toc-free">Vidlark is free and open source, for Mac and Windows. <a href="/how-to">How to get it</a></p>
    </aside>
    <div class="post-main">
      <figure class="post-cover"><img src="{esc(cover)}" alt="{esc(m["cover_alt"])}" width="{size[0]}" height="{size[1]}" fetchpriority="high" decoding="async"></figure>
      <div class="prose">
{post.html}
      </div>
{faq}{cta_box()}
    </div>
  </div>
</div>
</article>
{related_html}
</main>

{shell.tail()}"""


def render_index(posts: list[Post], shell: Shell) -> str:
    data = {"@context": "https://schema.org", "@graph": [
        {"@type": "Blog", "@id": BASE + "/blog#blog", "name": "Vidlark blog", "url": BASE + "/blog",
         "description": BLOG_DESCRIPTION, "inLanguage": "en", "publisher": publisher(),
         "blogPost": [{"@type": "BlogPosting", "headline": p.meta["title"], "url": p.url,
                       "datePublished": p.meta["date"].isoformat(), "dateModified": p.meta["updated"].isoformat(),
                       "image": BASE + p.meta["cover"],
                       "author": {"@type": "Person", "name": AUTHOR, "url": AUTHOR_URL}} for p in posts]},
        crumbs_data([("Home", "/"), ("Blog", "/blog")]),
    ]}
    head = shell.head(title=BLOG_TITLE, description=BLOG_DESCRIPTION, canonical=BASE + "/blog",
                      image="/assets/img/og/blog.jpg", image_alt="The Vidlark blog: guides to recording videos, free",
                      image_size=(1200, 630), theme=FIELD_HEX["sun"], data=data)
    counts = {}
    for p in posts:
        counts[p.meta["category"]] = counts.get(p.meta["category"], 0) + 1
    buttons = [f'<button type="button" data-filter="all" aria-pressed="true">All <span>{len(posts)}</span></button>']
    for name, (slug, colour) in CATEGORIES.items():
        if counts.get(name):
            buttons.append(f'<button type="button" id="{slug}" data-filter="{slug}" aria-pressed="false" '
                           f'style="--c:var(--{colour})"><i aria-hidden="true"></i>{esc(name)} <span>{counts[name]}</span></button>')
    cards = "\n".join(card(p, 2) for p in posts) or '<p class="muted">The first posts are on their way.</p>'
    return f"""{head}
<body>
{GENERATED.format(src="*.md")}
{shell.sprite}

<a class="skip" href="#main">Skip to the content</a>

{shell.nav("page")}

<main id="main">

<section class="band sun page-head blog-head">
  <div class="wrap">
    {crumbs_html([("Home", "/"), ("Blog", None)])}
    <h1>The Vidlark blog</h1>
    <p>{esc(BLOG_LEAD)}</p>
    <p class="feed-link"><a href="/blog/feed.xml"><svg aria-hidden="true"><use href="#i-rss"/></svg>Follow with RSS</a></p>
  </div>
</section>

<section class="band blog-list" id="posts" aria-label="Posts">
  <div class="wrap">
    <div class="cat-filter" role="group" aria-label="Show posts about" hidden>
      {"".join(buttons)}
    </div>
    <div class="post-cards">
{cards}
    </div>
  </div>
</section>

<section class="band lime close">
  <div class="wrap">
    <h2>Free, from the first take.</h2>
    <p>No account, no subscription, no watermark and no time limit. On a Mac, and on Windows in beta.</p>
    <div class="actions">
      <a class="btn" href="{GITHUB}"><svg aria-hidden="true"><use href="#i-github"/></svg>Get it on GitHub</a>
      <a class="btn ghost" href="/how-to">How to use it<svg aria-hidden="true"><use href="#i-arrow"/></svg></a>
    </div>
  </div>
</section>

</main>

{shell.tail()}"""


def render_strip(posts: list[Post]) -> str:
    if not posts:
        return ""
    cards = "\n".join(card(p, 3) for p in posts[:3])
    return ('<section class="band mist" id="from-the-blog" aria-labelledby="from-the-blog-title">\n  <div class="wrap">\n'
            '    <div class="strip-head"><h2 id="from-the-blog-title">From the blog</h2>'
            '<a class="btn ghost" href="/blog">All posts<svg aria-hidden="true"><use href="#i-arrow"/></svg></a></div>\n'
            f'    <div class="post-cards">\n{cards}\n    </div>\n  </div>\n</section>\n')


def rfc822(d: dt.date) -> str:
    days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
    return f"{days[d.weekday()]}, {d.day:02d} {d.strftime('%b')} {d.year} 00:00:00 +0000"


def render_feed(posts: list[Post]) -> str:
    x = lambda s: html.escape(str(s), quote=False)  # noqa: E731
    newest = max((p.meta["updated"] for p in posts), default=dt.date.today())
    items = []
    for p in posts[:50]:
        cover = local_file(p.meta["cover"])
        enclosure = (f'\n      <enclosure url="{esc(BASE + p.meta["cover"])}" length="{cover.stat().st_size}" '
                     f'type="image/{cover.suffix.lstrip(".").replace("jpg", "jpeg")}"/>' if cover else "")
        items.append(f"""    <item>
      <title>{x(p.meta["title"])}</title>
      <link>{p.url}</link>
      <guid isPermaLink="true">{p.url}</guid>
      <pubDate>{rfc822(p.meta["date"])}</pubDate>
      <category>{x(p.meta["category"])}</category>
      <description>{x(p.meta["description"])}</description>{enclosure}
    </item>""")
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Vidlark blog</title>
    <link>{BASE}/blog</link>
    <atom:link href="{BASE}/blog/feed.xml" rel="self" type="application/rss+xml"/>
    <description>{x(BLOG_DESCRIPTION)}</description>
    <language>en</language>
    <lastBuildDate>{rfc822(newest)}</lastBuildDate>
{chr(10).join(items)}
  </channel>
</rss>
"""


def git_date(path: Path):
    """The page's last change: today if it has uncommitted changes, else its last commit's date."""
    rel = str(path.relative_to(ROOT))
    try:
        dirty = subprocess.run(["git", "status", "--porcelain", "--", rel], cwd=ROOT, capture_output=True,
                               text=True, check=True).stdout.strip()
        if dirty:
            return dt.date.today()
        out = subprocess.run(["git", "log", "-1", "--format=%cs", "--", rel], cwd=ROOT, capture_output=True,
                             text=True, check=True).stdout.strip()
        if out:
            return dt.date.fromisoformat(out)
    except (OSError, subprocess.CalledProcessError, ValueError):
        pass
    return dt.date.fromtimestamp(path.stat().st_mtime)


def render_sitemap(posts: list[Post]) -> str:
    rows = []
    newest = max((p.meta["updated"] for p in posts), default=None)
    pages = sorted(SITE.glob("*.html"), key=lambda p: (p.name != "index.html", p.name))
    for page in pages:
        if page.name == "404.html" or 'name="robots" content="noindex' in page.read_text(encoding="utf-8"):
            continue
        loc = "/" if page.name == "index.html" else "/" + page.stem
        last = git_date(page)
        if page.name == "index.html" and newest and newest > last:
            last = newest  # the home page shows the latest posts
        rows.append((loc, last))
    if newest:
        blog_last = newest
    elif (BLOG_OUT / "index.html").exists():
        blog_last = git_date(BLOG_OUT / "index.html")
    else:
        blog_last = dt.date.today()
    rows.append(("/blog", blog_last))
    rows += [(p.path_url, p.meta["updated"]) for p in posts]
    body = "\n".join(f"  <url><loc>{BASE}{loc}</loc><lastmod>{d.isoformat()}</lastmod></url>" for loc, d in rows)
    return ('<?xml version="1.0" encoding="UTF-8"?>\n'
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + body + "\n</urlset>\n")


def update_home_strip(posts: list[Post], problems: Problems) -> bool:
    home = HOME.read_text(encoding="utf-8")
    a, b = home.find(STRIP_START), home.find(STRIP_END)
    if a < 0 or b < a:
        problems.error("website/index.html", "the blog strip markers are missing (<!-- blog:latest:start ... --> "
                                             "and <!-- blog:latest:end -->)")
        return False
    a = home.index("-->", a) + 3
    new = home[:a] + "\n" + render_strip(posts) + home[b:]
    return write(HOME, new)


# ---------------------------------------------------------------------------------------------
# Site check: every HTML page in website/

class PageScan(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.lang = None
        self.title = ""
        self.in_title = False
        self.meta = {}
        self.canonical = None
        self.h1 = 0
        self.ids = set()
        self.links = []  # (attr, url)
        self.no_alt = []
        self.jsonld = []
        self._ld = None

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if "id" in a:
            self.ids.add(a["id"])
        if tag == "html":
            self.lang = a.get("lang")
        elif tag == "title":
            self.in_title = True
        elif tag == "meta":
            key = a.get("name") or a.get("property")
            if key:
                self.meta[key] = a.get("content", "")
        elif tag == "link":
            if a.get("rel") == "canonical":
                self.canonical = a.get("href")
            if a.get("href"):
                self.links.append(("link", a["href"]))
        elif tag == "h1":
            self.h1 += 1
        elif tag == "a" and a.get("href"):
            self.links.append(("a", a["href"]))
        elif tag in ("img", "script", "source", "video") and (a.get("src") or a.get("poster")):
            if a.get("src"):
                self.links.append((tag, a["src"]))
            if a.get("poster"):
                self.links.append((tag, a["poster"]))
            if tag == "img" and "alt" not in a:
                self.no_alt.append(a.get("src"))
        if tag == "script" and a.get("type") == "application/ld+json":
            self._ld = []

    def handle_endtag(self, tag):
        if tag == "title":
            self.in_title = False
        if tag == "script" and self._ld is not None:
            self.jsonld.append("".join(self._ld))
            self._ld = None

    def handle_data(self, data):
        if self.in_title:
            self.title += data
        if self._ld is not None:
            self._ld.append(data)


def check_site(problems: Problems):
    scans = {}
    pages = sorted(p for p in SITE.rglob("*.html") if "assets" not in p.parts)
    for page in pages:
        text = page.read_text(encoding="utf-8")
        scan = PageScan()
        scan.feed(text)
        scans[page] = (scan, text)
    for page, (scan, text) in scans.items():
        where = str(page.relative_to(ROOT))
        noindex = "noindex" in scan.meta.get("robots", "")
        if EM_DASH in text:
            problems.error(where, f"has {text.count(EM_DASH)} em dash(es)")
        if scan.lang != "en":
            problems.error(where, 'the <html> tag needs lang="en"')
        if scan.h1 != 1:
            problems.error(where, f"has {scan.h1} h1 headings; a page needs exactly one")
        for src in scan.no_alt:
            problems.error(where, f"the image {src} has no alt attribute")
        if len(scan.title) > 60:
            problems.warn(where, f"<title> is {len(scan.title)} characters; keep it under 60")
        desc = scan.meta.get("description", "")
        if not noindex and not 140 <= len(desc) <= 160:
            problems.warn(where, f"meta description is {len(desc)} characters; aim for 140 to 160")
        if not noindex and not scan.canonical:
            problems.error(where, "has no canonical link")
        if not noindex and not scan.meta.get("og:image"):
            problems.error(where, "has no og:image")
        for block in scan.jsonld:
            try:
                json.loads(block)
            except json.JSONDecodeError as e:
                problems.error(where, f"a JSON-LD block does not parse: {e}")
        urls = [u for _, u in scan.links]
        urls += [scan.meta[k] for k in ("og:image", "twitter:image", "og:url") if scan.meta.get(k)]
        if scan.canonical:
            urls.append(scan.canonical)
        for url in urls:
            if url.startswith(("mailto:", "tel:", "javascript:")) or (
                    url.startswith(("http://", "https://")) and not url.startswith(BASE)):
                continue
            if url.startswith("#"):
                target, anchor = page, url[1:]
            else:
                target = local_file(url)
                anchor = url.split("#", 1)[1] if "#" in url else ""
                if target is None:
                    problems.error(where, f"the link {url} goes to no file in website/")
                    continue
            if anchor and target.suffix == ".html":
                ids = scans[target][0].ids if target in scans else set()
                if anchor not in ids:
                    problems.error(where, f"the link {url} points to #{anchor}, which is not on that page")


# ---------------------------------------------------------------------------------------------

def render_missing_covers(paths: list[Path]):
    for path in paths:
        text = path.read_text(encoding="utf-8")
        m = re.match(r"^---[ \t]*\n(.*?)\n---", text, re.S)
        if not m:
            continue
        try:
            meta = parse_front_matter(m.group(1))
        except ValueError:
            continue
        cover = str(meta.get("cover", ""))
        if cover.startswith("/assets/img/blog/") and not local_file(cover) and meta.get("title"):
            print(f"Rendering a cover for {path.stem}")
            subprocess.run(["node", str(ROOT / "Tools" / "blog_cover.js"), path.stem, str(meta["title"]),
                            str(meta.get("category", "Guides"))], cwd=ROOT, check=False)


def main():
    ap = argparse.ArgumentParser(description="Build the Vidlark blog, the feed and the sitemap, then check the site.")
    ap.add_argument("--check", action="store_true", help="check only; write nothing")
    ap.add_argument("--covers", action="store_true", help="render a cover for any post whose cover file is missing")
    ap.add_argument("--strict", action="store_true", help="treat warnings as errors")
    args = ap.parse_args()

    problems = Problems()
    sources = sorted(p for p in CONTENT.glob("*.md") if p.name.lower() != "readme.md")
    if args.covers and not args.check:
        render_missing_covers(sources)
    loaded = [load_post(p, problems) for p in sources]
    posts = [p for p in loaded if p is not None and not p.draft]
    posts.sort(key=lambda p: (p.meta["date"], p.meta["updated"], p.meta["title"]), reverse=True)
    slugs = {p.slug for p in posts}
    for p in posts:
        check_post_links(p, slugs, problems)

    written = []
    if not args.check and not problems.errors:
        shell = Shell(problems)
        expected = set()
        for p in posts:
            out = BLOG_OUT / f"{p.slug}.html"
            expected.add(out)
            if write(out, render_post(p, posts, shell)):
                written.append(out)
        # Remove pages this script made for posts that are gone or now drafts.
        if BLOG_OUT.exists():
            for old in BLOG_OUT.glob("*.html"):
                if old.name != "index.html" and old not in expected and \
                        "Generated by Tools/blog.py" in old.read_text(encoding="utf-8"):
                    old.unlink()
                    print(f"Removed {old.relative_to(ROOT)} (its post is gone or a draft)")
        for path, text in ((BLOG_OUT / "index.html", render_index(posts, shell)),
                           (BLOG_OUT / "feed.xml", render_feed(posts))):
            if write(path, text):
                written.append(path)
        if update_home_strip(posts, problems):
            written.append(HOME)
        if write(SITE / "sitemap.xml", render_sitemap(posts)):
            written.append(SITE / "sitemap.xml")

    check_site(problems)

    drafts = [p for p in loaded if p is not None and p.draft]
    print(f"{len(posts)} post(s){f', {len(drafts)} draft(s) skipped' if drafts else ''}.")
    if args.check:
        print("Checked only; nothing written.")
    elif problems.errors and not written:
        print("Nothing written: fix the errors below first.")
    else:
        print(f"{len(written)} file(s) changed" + (":" if written else "."))
        for w in written:
            print(f"  {w.relative_to(ROOT)}")
    for w in problems.warnings:
        print(f"WARNING  {w}")
    for e in problems.errors:
        print(f"ERROR    {e}")
    if problems.errors or (args.strict and problems.warnings):
        sys.exit(1)


if __name__ == "__main__":
    main()
